version: git.{build}

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
          ver: 2013
          generator: "Visual Studio 12 2013"
          configuration: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          ver: 2015
          generator: "Visual Studio 14 2015"
          configuration: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          ver: 2017
          generator: "Visual Studio 15 2017"
          configuration: Release
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          ver: 2019
          generator: "Visual Studio 16 2019"
          configuration: Release

install:
    - git clone https://github.com/DLR-TS/SUMOLibraries
    - set SUMO_LIBRARIES=%CD%\SUMOLibraries

build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir build_msvc%ver% &&
      cd build_msvc%ver% &&
      cmake .. -G"%generator%" -A x64 -DPYTHON_EXECUTABLE=C:\Python37-x64\python.exe &&
      cmake --build . --config %configuration%

matrix:
    fast_finish: true

artifacts:
    - path: bin
      type: zip 