# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '(tests|tools/contributed|tools/sumolib/scenario)/.*'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: '.*\.rtf'
    -   id: end-of-file-fixer
        exclude: '.*\.rtf'
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/igrr/astyle_py.git
    rev: v1.0.5
    hooks:
    -   id: astyle_py
        args: [--style=java --unpad-paren --pad-header --pad-oper --add-brackets --indent-switches --align-pointer=type]
        exclude: 'src/foreign/.*'
