language: c++

os: linux
dist: xenial

compiler:
  - gcc
  - clang

env:
  - TOOLCHAIN=autotools
  - TOOLCHAIN=cmake

matrix:
  include:
    - os: osx
      osx_image: xcode10.2 # Xcode 10.2.1; macOS 10.14
      compiler: clang
      env: TOOLCHAIN=cmake
    - os: linux
      compiler: gcc
      env: TOOLCHAIN=cmake-minimal

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake autoconf automake libtool libxerces-c-dev libfox-1.6-dev libgl1-mesa-dev libglu1-mesa-dev libgdal-dev libproj-dev libgtest-dev libgl2ps-dev python3-dev swig openjdk-8-jdk maven; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pushd /usr/src/gtest; sudo mkdir build; cd build; sudo cmake ..; sudo make; sudo cp libgtest* /usr/lib/; popd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xerces-c fox gl2ps; fi

script:
#  - if [[ "$CXX" == "clang++" ]]; then export CXXFLAGS="$CXXFLAGS -stdlib=libc++"; export LDFLAGS="$LDFLAGS -stdlib=libc++"; fi
  - if [[ "$TOOLCHAIN" == "autotools" ]]; then autoreconf -i && ./configure; fi
  - if [[ "$TOOLCHAIN" == "cmake" ]]; then mkdir cmake-build && cd cmake-build && cmake ..; fi
  - if [[ "$TOOLCHAIN" == "cmake-minimal" ]]; then mkdir cmake-build && cd cmake-build && cmake -DFOX_CONFIG= -DPROJ_LIBRARY= -DCHECK_OPTIONAL_LIBS=OFF ..; fi
  - make -j4
  - make traas
  - sudo make install
  - if [[ "$TOOLCHAIN" == "cmake" ]]; then make CTEST_OUTPUT_ON_FAILURE=1 examples test; fi
  - if [[ "$TOOLCHAIN" == "autotools" ]]; then make examples; SUMO_HOME=$TRAVIS_BUILD_DIR python $TRAVIS_BUILD_DIR/docs/examples/runAll.py; fi
