name: bibtex

on:
  workflow_dispatch:

jobs:
  bibtex_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install bibtexparser --pre

      - name: Run script
        run: python ${{ github.workspace }}/tools/build_config/bibtexUpdate.py --bibtex-input ${{ github.workspace }}/docs/sumo.bib --bibtex-output ${{ github.workspace }}/docs/sumo.bib --cited-works "b1914c912dea62703856d89fe3724675a6139b71" "0e62ded610aeb17cc65f9f7159477e48248a98a2" --min-citations 100 --exclude-media "SUMO Conference Proceedings" "International Conference on Simulation of Urban Mobility" "arXiv.org"

      - name: Pull request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update SUMO bibtex file #13811'
          title: 'Update SUMO bibtex file'
          add-paths: ${{ github.workspace }}/docs/sumo.bib
          draft: always-true
          base: main
          branch: sumo-patches
          signoff: true
          body: 'Add latest influential papers from SemanticScholar referencing SUMO (auto-generated by Github Action).'
