name: windows

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '25 1 * * *'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [plain, extra]
    env:
      CC: cl
      CXX: cl

    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v2
      with:
        path: sumo
        fetch-depth: 0

    - name: Fetching SUMO tags
      run: |
        cd sumo
        git fetch --tags --force

    - name: Cloning SUMO Libraries
      uses: actions/checkout@v2
      with:
        repository: DLR-TS/SUMOLibraries 
        path: sumolibraries

    - name: "Set up compiler cache"
      uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\AppData\Local\Mozilla\sccache\cache
        key: ${{ matrix.build-type }}-${{ github.head_ref }}-${{ github.run_number }}
        restore-keys: |
          ${{ matrix.build-type }}-${{ github.head_ref }}-
          ${{ matrix.build-type }}-

    # required for CMake to find Ninja
    - name: "Set up MSVC Developer Command Prompt"
      uses: seanmiddleditch/gha-setup-vsdevenv@v3

    - name: Configuring SUMO plain build
      if: matrix.build-type == 'plain'
      run: |
        python -m pip install wheel
        cd sumo
        mkdir build_msvc
        cd build_msvc
        cmake .. -GNinja -DCHECK_OPTIONAL_LIBS=false

    - name: Building SUMO plain
      if: matrix.build-type == 'plain'
      run: |
        cd sumo
        cmake --build build_msvc --config Release

    - name: Building SUMO extra
      if: matrix.build-type == 'extra'
      run: |
        cd sumo
        mkdir build_msvc
        cd build_msvc
        cmake -DFMI=ON .. -GNinja -DCHECK_OPTIONAL_LIBS=true
        cmake --build . --config Release

    - name: Building TraaS
      run: |
        cd sumo/build_msvc
        cmake --build . --config Release --target traas

    - name: Uploading artifacts (SUMO binaries)
      uses: actions/upload-artifact@v1
      with:
        name: Windows-${{ matrix.build-type }}
        path: sumo/bin
        retention-days: 30

    - name: Plain examples and tests
      if: matrix.build-type == 'plain'
      run: |
        cd sumo/build_msvc
        $env:TEXTTEST_TMP = "D:/texttest/1"
        $env:TEXTTEST_CI_APPS = "-a activitygen,dfrouter,duarouter,jtrrouter,sumo"
        ctest -R texttest --verbose
        $env:TEXTTEST_TMP = "D:/texttest/2"
        $env:TEXTTEST_CI_APPS = "-a marouter,netgen,od2trips,polyconvert,netconvert"
        ctest -R texttest --verbose

    - name: Examples and extra tests
      if: matrix.build-type == 'extra'
      run: |
        python -m pip install pyproj Rtree ezdxf pulp pandas matplotlib scipy
        cd sumo/build_msvc
        cmake --build . --config Release --target examples
        $env:TEXTTEST_TMP = "D:/texttest"
        $env:TEXTTEST_CI_APPS = "-a complex,tools,traci"
        ctest --build-config Release --verbose

    - name: Uploading test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: texttesttmp-${{ matrix.build-type }}
        path: D:/texttest
        if-no-files-found: warn

    - name: Building FMU Compliance Checker
      if: matrix.build-type == 'extra'
      run: |
        git clone https://github.com/modelica-tools/FMUComplianceChecker.git fmuChecker
        cd fmuChecker
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ..
        cmake --build . --config MinSizeRel --target install

    - name: Checking sumo-fmi2.fmu
      if: matrix.build-type == 'extra'
      run: |
        $env:Path = "$env:Path;$pwd\sumo\bin"
        echo $env:Path
        cd sumo
        ../fmuChecker/install/fmuCheck.win64 bin/sumo-fmi2-win64.fmu 

    - name: Uploading FMI 2.0 FMU artifacts
      if: matrix.build-type == 'extra'
      uses: actions/upload-artifact@v1
      with:
        name: sumo-fmi2-win64
        path: sumo/bin/sumo-fmi2-win64.fmu 
